#######################################################
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
joint_motor1_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_right_prop
    pid: {p: 10000.0, i: 1.0, d: 1000.0}

joint_motor2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_left_prop
    pid: {p: 10000.0, i: 1.0, d: 1000.0}
    
joint_motor3_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_left_prop
    pid: {p: 10000.0, i: 1.0, d: 1000.0}

joint_motor4_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_right_prop
    pid: {p: 10000.0, i: 1.0, d: 1000.0}
#######################################################

# joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50

# joint_motor_controller:
#     type: velocity_controllers/JointGroupVelocityController
#     joints: 
#         - joint_front_right_prop
#         - joint_front_left_prop
#         - joint_back_left_prop
#         - joint_back_right_prop
#     gains:
#         joint_front_right_prop: {p: 1000, i: 1, d: 1000}
#         joint_front_left_prop: {p: 10000, i: 1, d: 1000}
#         joint_back_left_prop: {p: 10000, i: 1, d: 1000}
#         joint_back_right_prop: {p: 10000, i: 1, d: 1000}
#############################################################

#publish all joint states
# ros_gui:
#     joint_state_controller:
#         type: joint_state_controller/JointStateController
#         publish_rate: 50
# #position controller
# joint_motor_controller:
#     type: velocity_controllers/JointGroupVelocityController
#     joint: joint_front_right_prop
#     pid: {p: 1000, i: 1, d: 1000}
# joint_motor_controller:
#     type: velocity_controllers/JointGroupVelocityController
#     joint: joint_front_left_prop
#     pid: {p: 1000, i: 1, d: 1000}
# joint_motor_controller:
#     type: velocity_controllers/JointGroupVelocityController
#     joint: joint_back_left_prop
#     pid: {p: 1000, i: 1, d: 1000}
# joint_motor_controller:
#     type: velocity_controllers/JointGroupVelocityController
#     joint: joint_back_right_prop
#     pid: {p: 1000, i: 1, d: 1000}
###################################################

# /gazebo_ros_control:
#     pid_gains:
#         joint_front_right_prop:
#             p:10
#             i:1
#             d:10
#         joint_front_left_prop:
#             p:10
#             i:1
#             d:10
#         joint_back_left_prop:
#             p:10
#             i:1
#             d:10
#         joint_back_right_prop:
#             p:10
#             i:1
#             d:10